export const SHOW_LOADER = 'SHOW_LOADER'
export const GET_CATS = 'GET_CATS'
export const SET_CATS = 'SET_CATS'
export const FETCHING = 'FETCHING'
export const GET_FAVORITE_CATS = 'GET_FAVORITE_CATS'
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT'
export const DELETE_CAT = 'DELETE_CAT'
